import { useEffect, useState } from 'react'
import type { DesktopBridge } from '../../shared/ipc-contracts.ts'
import type { AppPreferences, AppPreferencesSnapshot } from '../../shared/app-preferences.ts'

export function AppPreferencesPage({ bridge }: { bridge?: DesktopBridge }) {
  const [base, setBase] = useState<AppPreferencesSnapshot | null>(null), [draft, setDraft] = useState<AppPreferences | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('')
  const load = async () => { if (!bridge) return; setBusy(true); const r = await bridge.invoke('app.preferences.read', {}); if (r.ok) { setBase(r.value); setDraft(r.value.preferences); setError('') } else setError(r.error.message); setBusy(false) }
  useEffect(() => { void load() }, [bridge])
  const change = (fn: (p: AppPreferences) => AppPreferences) => setDraft(p => p ? fn(p) : p)
  async function save(reset = false) { if (!bridge || !base || !draft) return; setBusy(true); setError(''); setNotice(''); const r = reset ? await bridge.invoke('app.preferences.reset', { expectedRevision: base.revision }) : await bridge.invoke('app.preferences.update', { expectedRevision: base.revision, preferences: draft }); if (r.ok) { setBase(r.value.snapshot); setDraft(r.value.snapshot.preferences); setNotice(r.value.outcome === 'conflict' ? 'Preferences changed elsewhere. The latest saved version is shown; review before saving again.' : r.value.outcome === 'read-only' ? 'Preferences are read-only in this environment.' : reset ? 'Preferences restored.' : 'Preferences saved.') } else setError(r.error.message); setBusy(false) }
  if (!draft) return <section className="preferences-page"><h1>Application preferences</h1><p>Loading saved preferences…</p>{error && <p role="alert" className="inline-error">{error}</p>}<button className="secondary-button" onClick={() => void load()} disabled={busy}>Retry</button></section>
  const toggle = (label: string, checked: boolean, onChange: (v: boolean) => void) => <label className="preference-row"><span>{label}</span><input type="checkbox" checked={checked} disabled={busy || base?.readOnly} onChange={e => onChange(e.target.checked)} /></label>
  return <section className="preferences-page"><div className="settings-heading"><div><div className="eyebrow">APPLICATION</div><h1>Preferences</h1><p>These settings affect this app only, not Pi or your workspace.</p></div><span className="revision-tag">Revision {base?.revision}{base?.readOnly ? ' · read only' : ''}</span></div>
    {base?.diagnostic && <p className="diagnostic" role="status">{base.diagnostic.message}</p>}
    <div className="settings-grid"><section className="settings-card"><h2>Appearance</h2><label>Theme<select value={draft.appearance.theme} disabled={busy || base?.readOnly} onChange={e => change(p => ({...p, appearance:{...p.appearance, theme:e.target.value as AppPreferences['appearance']['theme']}}))}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Density<select value={draft.appearance.density} disabled={busy || base?.readOnly} onChange={e => change(p => ({...p, appearance:{...p.appearance, density:e.target.value as AppPreferences['appearance']['density']}}))}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Accent color<input type="color" value={draft.appearance.accentColor} disabled={busy || base?.readOnly} onChange={e => change(p => ({...p, appearance:{...p.appearance, accentColor:e.target.value}}))}/></label></section>
    <section className="settings-card"><h2>Layout</h2>{toggle('Show sidebar',draft.layout.sidebar.visible,v=>change(p=>({...p,layout:{...p.layout,sidebar:{...p.layout.sidebar,visible:v}}})))}<label>Sidebar width <output>{draft.layout.sidebar.width}px</output><input type="range" min="180" max="360" value={draft.layout.sidebar.width} disabled={busy || base?.readOnly} onChange={e=>change(p=>({...p,layout:{...p.layout,sidebar:{...p.layout.sidebar,width:Number(e.target.value)}}}))}/></label>{toggle('Show inspector',draft.layout.inspector.visible,v=>change(p=>({...p,layout:{...p.layout,inspector:{...p.layout.inspector,visible:v}}})))}{toggle('Show terminal',draft.layout.terminal.visible,v=>change(p=>({...p,layout:{...p.layout,terminal:{...p.layout.terminal,visible:v}}})))}</section>
    <section className="settings-card"><h2>Notifications & access</h2>{toggle('Enable notifications',draft.notifications.enabled,v=>change(p=>({...p,notifications:{...p.notifications,enabled:v}})))}{toggle('Play notification sounds',draft.notifications.sound,v=>change(p=>({...p,notifications:{...p.notifications,sound:v}})))}<label>Keyboard mode<select value={draft.accessibility.keyboardMode} disabled={busy || base?.readOnly} onChange={e=>change(p=>({...p,accessibility:{...p.accessibility,keyboardMode:e.target.value as AppPreferences['accessibility']['keyboardMode']}}))}><option value="standard">Standard</option><option value="vim">Vim</option></select></label>{toggle('Reduce motion',draft.accessibility.reducedMotion,v=>change(p=>({...p,accessibility:{...p.accessibility,reducedMotion:v}})))}</section>
    <section className="settings-card"><h2>Privacy</h2>{toggle('Save drafts on this device',draft.privacy.persistDrafts,v=>change(p=>({...p,privacy:{...p.privacy,persistDrafts:v}})))}<label>Trace retention<select value={draft.privacy.traceRetentionDays} disabled={busy || base?.readOnly} onChange={e=>change(p=>({...p,privacy:{...p.privacy,traceRetentionDays:Number(e.target.value) as AppPreferences['privacy']['traceRetentionDays']}}))}><option value="0">Do not retain</option><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label>{toggle('Allow diagnostic sharing when requested',draft.privacy.shareDiagnostics,v=>change(p=>({...p,privacy:{...p.privacy,shareDiagnostics:v}})))}</section></div>
    {error && <p role="alert" className="inline-error">{error}</p>}{notice && <p role="status" className="success-note">{notice}</p>}<div className="settings-actions"><button className="text-button" disabled={busy || base?.readOnly} onClick={() => { setDraft(base?.preferences ?? null); setNotice('Unsaved changes discarded.') }}>Discard changes</button><button className="secondary-button" disabled={busy || base?.readOnly} onClick={() => void save(true)}>Reset defaults</button><button className="primary-button" disabled={busy || base?.readOnly} onClick={() => void save()}>{busy ? 'Saving…' : 'Save preferences'}</button></div>
  </section>
}
